---
default:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
  DOCKER_TLS_CERTDIR: '/certs'
  IMAGE_TAG: registry.gitlab.com/kevindurb/box:latest

stages:
  - build

build-container:
  stage: build
  script:
    - docker build -t $IMAGE_TAG -f ./Containerfile .
    - docker push $IMAGE_TAG
