---
default:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

variables:
  DOCKER_TLS_CERTDIR: '/certs'
  BUILD_TAG: registry.gitlab.com/kevindurb/box:$CI_BUILD_REF_NAME
  RELEASE_TAG: registry.gitlab.com/kevindurb/box:latest

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build -t $BUILD_TAG -f ./Containerfile .
    - docker push $BUILD_TAG

release:
  stage: release
  script:
    - docker pull $BUILD_TAG
    - docker tag $BUILD_TAG $RELEASE_TAG
    - docker push $RELEASE_TAG
  only:
    - main
