---
default:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker info

variables:
  DOCKER_TLS_CERTDIR: '/certs'

stages:
  - build

build-container:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/kevindurb/box -f ./Containerfile .
    - docker push registry.gitlab.com/kevindurb/box
